// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2024/10/12 10:39:18
const configMerger = require("/Users/xinyudai/nuxt3-website/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{"height":{"100":"25rem","104":"26rem"}},"screens":{"sm":"640px","md":"768px","lg":"1024px","xl":"1280px","2xl":"1536px"}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/xinyudai/nuxt3-website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/xinyudai/nuxt3-website/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/xinyudai/nuxt3-website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/xinyudai/nuxt3-website/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/xinyudai/nuxt3-website/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/xinyudai/nuxt3-website/plugins/**/*.{js,ts,mjs}","/Users/xinyudai/nuxt3-website/composables/**/*.{js,ts,mjs}","/Users/xinyudai/nuxt3-website/utils/**/*.{js,ts,mjs}","/Users/xinyudai/nuxt3-website/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/xinyudai/nuxt3-website/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/xinyudai/nuxt3-website/app.config.{js,ts,mjs}"] }));

module.exports = config
