// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2024/10/11 16:53:52
const configMerger = require("/Users/xinyudai/alone-blog-nuxt3/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/xinyudai/alone-blog-nuxt3/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/xinyudai/alone-blog-nuxt3/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/xinyudai/alone-blog-nuxt3/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/xinyudai/alone-blog-nuxt3/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/xinyudai/alone-blog-nuxt3/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/xinyudai/alone-blog-nuxt3/plugins/**/*.{js,ts,mjs}","/Users/xinyudai/alone-blog-nuxt3/composables/**/*.{js,ts,mjs}","/Users/xinyudai/alone-blog-nuxt3/utils/**/*.{js,ts,mjs}","/Users/xinyudai/alone-blog-nuxt3/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/xinyudai/alone-blog-nuxt3/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/xinyudai/alone-blog-nuxt3/app.config.{js,ts,mjs}"] }));

module.exports = config
